name: Push images on main branch update

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build NGINX
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2
      - name: Build Docker images
        env:
          TAG: latest
          EXPOSED_PORT: 443
        run: docker-compose build
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push images to GitHub Container Registry
        env:
          TAG: latest
        run: docker-compose push
